### ISSUE TITLE
Add CBOR support

### ISSUE THREAD

**Issue by drasko** [cisco/senmlCat#16]
This is feature request for CBOR support. Binary format is important for battery-constrained devices.

**Comment by fluffy** [comment]
I'd love it fi someone sent a patch to add CBOR. On some projects they have found that compressed JSON used less power and network bandwidth than CBOR but totally agree with you it would be great to have CBOR.

**Comment by drasko** [comment]
Maybe compressed JSON can be more economic, but SenML spec specifies only CBOR as a binary solution, AFAIK. So per my understanding we can not use compressed JSON and we must have CBOR implementation.

**Comment by fluffy** [comment]
It now supports CBOR
